### ISSUE TITLE
Demos giving error due to mismatch of arguments.

### ISSUE THREAD

**Issue by marahman** [SheffieldML/GPclust#1]
Hi,
I was trying to execute some demo files using both 'master' and 'devel' branch of GPy.
But most of the demos are breaking giving me the following error.
Thanks.

In [1]: run MOHGP_sine_demo.py
/home/muhammad/mlprojects/GPy/GPy/util/linalg.py:48: UserWarning: warning: caught this exception:'module' object has no attribute '_dotblas'
##   warnings.warn("warning: caught this exception:" + str(e))

TypeError                                 Traceback (most recent call last)
/home/muhammad/mlprojects/colvb/examples/MOHGP_sine_demo.py in <module>()
     37 #Ky2 = kern.white(1,0.01)
     38 Ky = Ky1 + Ky2
---> 39 m = MOHGP(X,Kf,Ky,Y, K=Nclust, prior_Z = 'DP', alpha=alpha)
     40 #m.ensure_default_constraints()
     41 #m.checkgrad(verbose=1)

/home/muhammad/mlprojects/GPy/GPy/core/parameterization/parameterized.py in **call**(self, _args, *_kw)
     17         self._in_init_ = True
     18         #import ipdb;ipdb.set_trace()
---> 19         self = super(ParametersChangedMeta, self).**call**(_args, *_kw)
     20         logger.debug("finished init")
     21         self._in_init_ = False

/home/muhammad/mlprojects/colvb/colvb/MOHGP.pyc in **init**(self, X, kernF, kernY, Y, K, alpha, prior_Z)
     33         self.YTY = np.dot(self.Y.T,self.Y)
     34 
---> 35         collapsed_mixture.**init**(self, N, K, prior_Z, alpha)
     36 
     37     def _set_params(self,x):

/home/muhammad/mlprojects/colvb/colvb/col_mix.pyc in **init**(self, N, K, prior_Z, alpha)
     34         self.set_vb_param(np.random.randn(self.N*self.K))
     35 
---> 36         col_vb.**init**(self)
     37 
     38     def set_vb_param(self,phi_):

/home/muhammad/mlprojects/colvb/colvb/col_vb.pyc in **init**(self)
     23     def **init**(self):
     24         """"""
---> 25         GPy.core.model.Model.**init**(self)
     26 
     27         #stuff for monitoring the different methods

TypeError: **init**() takes exactly 2 arguments (1 given)

**Comment by lawrennd** [comment]
Hi Arif, Did you manage to resolve this?

**Comment by marahman** [comment]
Hi Neil,
I couldn't fix the issue in "colvb" but I solved "my problem" using "GPclust".
With minor modification the demos work fine using GPclust and we used it while working on our gene expression data of MND.
Regards,
Arif
